### ISSUE TITLE
POST http://localhost:55591/auth/facebook 404 (Not Found)

### ISSUE THREAD

**Issue by amitsinha559** [sahat/satellizer#598] opened 2015-10-14 09:15 UTC
getting this error

POST http://localhost:55591/auth/facebook 404 (Not Found)

What can I do ?

**Comment by Chakrakin** [comment] 2015-10-14 15:23
guess you need a server that handles the authentication process

examples can be looked here: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js

**Comment by fordg** [comment] 2015-11-09 08:36
@Chakrakin How to use its ?

**Comment by sahat** [comment] 2015-11-09 18:07
Duplicate of #632.

**Closed by sahat** 2015-11-09 18:07 UTC

**Comment by sahat** [comment] 2015-11-09 18:10
Are README instructions really that unhelpful that people just skip over server-side examples and just assume authorization will magically work on client-side only?
