### ISSUE TITLE
Can't login with facebook by safari on iOS 8.1

### ISSUE THREAD

**Issue by austintodo** [sahat/satellizer#322] opened 2015-03-14 14:35 UTC
I'm using my iPhone to login in the sample site:  
https://satellizer.herokuapp.com, but after clicking facebook button in login panel, a new window jumps out, and it shows nothing and does nothing. When I check the tabs in safari, there're actually two tabs, one showing the facebook,google,...etc button login panel (which is apparently the original one), and the other showing nothing (which should be redirect to the original one in desktop version). Does anyone have the same issue on iPhone safari?

**Comment by sahat** [comment] 2015-03-15 01:19
Works fine here. I just tested it on iOS 8.1 and Safari.

**Comment by austintodo** [comment] 2015-03-19 06:54
Hi: it turns out it's the issue from iOS 8.1
Upgrading to iO 8.1.1 or above could solve this problem. Just fyi.
Ref: http://stackoverflow.com/questions/25804730/window-close-doesnt-work-on-ios-8-gm-seed

**Comment by sahat** [comment] 2015-03-20 16:39
I was running iOS 8.1.2 which explains why I was not able to reproduce this issue. Alright, since it is not related to Satellizer I am closing this issue.

**Closed by sahat** 2015-03-20 16:39 UTC
