### ISSUE TITLE
CORS bug with Safari

### ISSUE THREAD

**Issue by redwood-egarcea** [sahat/satellizer#439] opened 2015-05-29 18:19 UTC
Safari throws errors on loop when satellizer opens any new window.
![screen shot 2015-05-29 at 2 15 45 pm](https://cloud.githubusercontent.com/assets/8050644/7889400/559aee9a-060d-11e5-8169-49fa2e07a354.png)

**Comment by sahat** [comment] 2015-06-01 01:08
I am surprised that Safari opens a new popup window for you. Not sure if it's related but my Safari browser opens a new tab instead of a popup, and authentication works without any issues.

Are you using Safari on a personal computer or at work / public location?

**Comment by redwood-egarcea** [comment] 2015-06-01 13:38
Are you running the latest version of Safari? Version 8.0.6 (10600.6.3) I was able to reproduce it both on a public and private connections. I tested to ensure no firewall rules could have caused the errors. 
![safari_cors_bug](https://cloud.githubusercontent.com/assets/8050644/7913997/ed6f35b0-0841-11e5-9aa2-6cff30780901.gif)

**Comment by sahat** [comment] 2015-06-05 08:35
I was able to reproduce the error, but don't have a solution on how to fix it. This seems to be happening only in Safari.

I know where the error is coming from, but still, not sure why, considering that other browsers don't complain about this issue.

```js
polling = $interval(function() {
            try {
              var documentOrigin = document.location.host;
              var popupWindowOrigin = popup.popupWindow.location.host;

              if (popupWindowOrigin === documentOrigin && (popup.popupWindow.location.search || popup.popupWindow.location.hash)) {
                var queryParams = popup.popupWindow.location.search.substring(1).replace(/\/$/, '');
                var hashParams = popup.popupWindow.location.hash.substring(1).replace(/[\/$]/, '');
                var hash = utils.parseQueryString(hashParams);
                var qs = utils.parseQueryString(queryParams);

                angular.extend(qs, hash);

                if (qs.error) {
                  deferred.reject({ error: qs.error });
                } else {
                  deferred.resolve(qs);
                }

                //popup.popupWindow.close();
                $interval.cancel(polling);
              }
            } catch (error) {
            }
            ...
```

**Comment by sahat** [comment] 2015-06-06 00:47
I am going to close this issue since I don't think there is any way to supress those browser exceptions. In any case, it shouldn't cause any problems. As soon as you sign-in with your OAuth provider, it will redirect you back to your app with `code` or `access_token` parameters in the URL. After Satellizer obtains those params, the popup will be closed.

**Closed by sahat** 2015-06-06 00:47 UTC
